### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by thecodeduchess** [Bossmeem/f1-3-c2p1-colmar-academy#4]
**Grade: Exceeds Expectations**

**Summary:** First, I test your project by downloading it and viewing it in my own browser. Next, I go step by step with your page against the requirements. I really enjoyed looking through your project. It has the perfect balance and combination of color, but not too much. The addition design combinations add a nice flair to the Colmar project! 

The code was easy to follow. Both desktop and mobile versions functioned properly.

 I think you have an excellent eye for design and detail. You are ready to move forward to your next project and we look forward to seeing what you come up with next.

**Comment by Bossmeem** [comment]
thank you so much! This course has been amazing.
